---

- name: common-desktop
  src: https://github.com/hackwish/ansible-common-desktop.git
  version: ubuntu-2004

- name: ohmyzsh
  src: https://github.com/hackwish/ansible-ohmyzsh.git

- name: cloudalchemy.node-exporter
  src: cloudalchemy.node-exporter

- name: bihealth.python3
  src: bihealth.python3

# - name: docker
#   src: https://github.com/hackwish/ansible-docker.git

# - name: rke
#   src: https://github.com/hackwish/ansible-rke.git

# - name: kompose-converter
#   src: https://github.com/hackwish/ansible-kompose-converter.git

# - name: rancher2-cli
#   src: https://github.com/hackwish/ansible-rancher2-cli.git

# - name: capistrano
#   src: https://github.com/hackwish/ansible-capistrano.git

# - name: ibmcloud
#   src: https://github.com/hackwish/ansible-ibmcloud.git
  
# - name: azurecli
#   src: https://github.com/hackwish/ansible-role-azurecli.git

# - name: andrewrothstein.kubernetes-helm
#   src: andrewrothstein.kubernetes-helm

# - name: andrewrothstein.kubectl
#   src: andrewrothstein.kubectl

# - name: gantsign.minikube
#   src: gantsign.minikube

# - name: rgibert.valve_steam
#   src: rgibert.valve_steam

# - name: geerlingguy.packer
#   src: geerlingguy.packer

# - name: andrewrothstein.vagrant
#   src: andrewrothstein.vagrant

# - name: andrewrothstein.terraform
#   src: andrewrothstein.terraform
